source 'https://rubygems.org'

gem 'puppet', '>= 7.0', '< 9.0'
gem 'puppetlabs_spec_helper', '~> 7.0'
gem 'metadata-json-lint', '~> 3.0'
gem 'puppet-lint', '~> 4.0'
gem 'rubocop', '~> 1.70', require: false
